@startuml

start

:Choose Option;
if () is (Update all Apps) then
  :Update all Apps;
else (Search App)
    :Search App;

    if () then (available)
        :Display App;
        :Choose Option;
        switch ()
        case (Install)
        :Install App;
        case (Uninstall)
        :Uninstall App;
        case (Update)
        :Update App;
        endswitch
    else (unavailable)
        :Show Error;
        detach
    endif
endif

stop

@enduml