@startuml

autonumber
hide footbox

actor User
participant appStore as "App Store"

User --> appStore++: getInstalledApps
appStore --> User: return App[]
User --> appStore: updateApps
appStore --> User--: return

@enduml