@startuml

actor User as user

package "App Store" {
    left to right direction

    usecase install as "Install"
    usecase uninstall as "Uninstall"
    usecase update as "Update"
    usecase updateSubset as "Update subset\n of Apps"
    usecase updateAll as "Update all Apps"
    usecase findApp as "Search for App
    --
    found results
    no results
    "

    usecase "Select App" as selectApp
    usecase "Show Error" as showError

    user -- update
    user -- findApp

    update <|-- updateAll
    update <|-- updateSubset

    findApp <.. selectApp : "<<extend>>\n (found results)"
    findApp <.. showError : "<<extend>>\n (no results)"

    selectApp <.. install : "<<extend>>\n (install)"
    selectApp <.. uninstall : "<<extend>>\n (uninstall)"
}

@enduml