@startuml

autonumber
hide footbox

participant user as "User"
participant appStore as "App Store"

user --> appStore: searchForApp
appStore --> user: return App[]
user --> appStore: selectApp
appStore --> appStore: install/uninstall
appStore --> user: return

@enduml