@startuml

skinparam classAttributeIconSize 0

class App {
    -name : String
    -developer : String
    -version : String
    +isUpToDate(): boolean
}

class AppStore {
    -allApps : App[]
    -installedApps : App[]

    +install(app: App): void
    +uninstall(app: App): void
    +update(app: App): void
    +searchForApp(query: String): App[]
    +selectApp(apps: App[]) : App
    +updateApps(): void
}

AppStore *-- "0..*" App : has

@enduml
