@startuml

actor User as user

package "App Store" {
    left to right direction

    usecase install as "Install App"
    usecase uninstall as "Uninstall App"
    usecase update as "Update"
    usecase updateSubset as "Update Subset"
    usecase updateAll as "Update all Apps"
    usecase findApp as "Find App
    --
    App available
    App unavailable
    "

    usecase "Display App" as displayApp
    usecase "Show Error" as showError

    user -- install
    user -- uninstall
    user -- update
    user -- findApp

    update <|-- updateAll
    update <|-- updateSubset

    findApp <.. displayApp : "<<extend>>\n (App available)"
    findApp <.. showError : "<<extend>>\n (App unavailable)"
}

@enduml