@startuml

start

:Choose Option;
if () is (Update) then
  :Make Selection;
  if () then (all)
    :Update
    all Apps;
  else (subset)
    :Update
    subset of
    Apps;
  endif
else (Search)
    :Search App;

    if () then (found results)
        :Show List of Results;
        :Select App;
        :Choose Option;
        switch ()
        case (Install)
        :Install;
        case (Uninstall)
        :Uninstall;
        endswitch
    else (no results)
        :Show Error;
        detach
    endif
endif

stop

@enduml